services:
  create-user:
    build: ./create-user-service
    volumes:
      - ./create-user-service:/app
    ports:
      - "3001:3001"
    networks:
      - internal-network

  edit-user:
    build: ./edit-user-service
    volumes:
      - ./edit-user-service:/app
    ports:
      - "3002:3002"
    networks:
      - internal-network

  delete-user:
    build: ./delete-user-service
    volumes:
      - ./delete-user-service:/app
    ports:
      - "3003:3003"
    networks:
      - internal-network

networks:
  internal-network:
